[네비게이션 / 상세페이지] 컴포넌트 생성, 초기 레이아웃 및 기능 구현
wecode-bootcamp-korea/26-1st-LIKE-frontend pull request #1
Opened 2021-11-02 14:59 UTC by tomlim2

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 네비게이션 레이아웃, 목업 데이터 연동 등 기능 일부 구현
- 상세페이지 레이아웃  및 기능 일부 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 레이아웃 작업 초안 완료
- 네비게이션
- 상세페이지

2. 네비게이션 목업 데이터와 연동하여 카테고리 메뉴 생성

3. 로그인 컴포넌트 사용 준비
- 테스트용 로그인 토글 기능 추가
- `/detail` 혹은 `/testNav`에서 확인 가능 (`/detail`, `/testNav` 화면 오른쪽 위에 로그인 버튼이 있습니다.)

4. 상세페이지 수량 input 기능 구현
- `+`, `-` 버튼 클릭시 수량 1씩 변화
- 버튼을 이용해서는 최소 1까지만 입력가능
- input에 숫자만 입력된다. 
- 공란일때는 1으로 변환된다.
- `/detail`, 수량 옆 1, -, +에서 테스트 가능

5. 상세페이지, 로그인컴포넌트와 네비게이션 연동
- 상세페이지에 네비게이션과 테스트용 로그인 컴포넌트 추가

## :: 성장 포인트
- 목업데이터와 연동시키며 네비게이션 카테고리 메뉴를 구현시키면서 이것을 어떻게 메인 페이지와 연동시킬지 고민하기 시작했습니다.
- 상세페이지 수량 문자열 입력 제한시키는 과정에서 regular expression을 사용했고 수량에서 0이하로 내려갈때 1로 변환하는 기능 구현중 `preState`를 처음 써봤습니다.

<br />

## :: 기타 질문 및 특이 사항
:)

2021-11-03 02:10 UTC, younuk23 commented
- PR 제목 양식 맞춰주세요!
- 구현사항 설명 너무 정성스럽게 잘 작성해주셨네요! 조금 더 첨언하자면 구현결과 뿐만 아니라 어떻게(HOW)에 초점을 더 맞춰서 작성해주시는 부분도 있으면 더 좋을것 같습니다!
구현사항을 잘 적으면서 내가 어떻게 구현했는지 스스로 이해도를 점검해볼 수 있으며 나중에 내가 어떤 고민을 하고 문제를 어떻게 해결했는지 점검해보면서 스스로를 회고해볼 수 있는 좋은 자산이 됩니다!

2021-11-03 02:12 UTC, younuk23 commented
아이콘 만들기 위해 react-icons.github.io라는 외부 라이브러리를 사용했습니다. 이런 라이브러리 설치 및 제거 사항이 나올때는 제가 쓴 feature/ 에서 쓰는게 좋나요? 아님 다른 브런치를 만들어서 푸쉬하는게 좋나요?
=> 작업하시는 브랜치에서만 사용되고 동시간대에 작업중인 다른 브랜치에서는 사용할 일이 없으면 작업 브랜치에서 설치하시는게 좋고 만약 이 라이브러리를 현재 작업중인 다른 브랜치에서도 필요하다고 하면 설치하는 브랜치만 따로 파서 빠르게 마스터에 머지시킨 후에 각자 작업하는게 좋습니다!! 그리고 branch 이름은 이제 작성자 이름이 아닌 기능이 드러나도록 작성해주세요 예시) `feature/nav`

2021-11-03 02:50 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요 연수님!!

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Menu/MenuItem.js
> +      <li className="menuItem">
네스팅을 통해서 이 컴포넌트의 스타일이 다른 컴포넌트에게 영향을 미치지 않도록 컴포넌트의 최상위 태그의 className은 컴포넌트 명과 동일하게 해주세요 일반적으로 className은 팀 컨벤션에 따라 camelCase또는 snake_case로 짓는게 일반적이지만 최상위 태그의 경우에는 컴포넌트 명과 동일하게 PascalCase로 지어주는 게 좋습니다(유니크하게 지어서 다른 className과 중복되지 않게 하기 위해서)

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Menu/MenuList.js
> +      <div className="menu">
최상위 className이 컴포넌트와 동일하지 않고 한단계 더 싸여져있네요! 수정해주세요

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Menu/MenuList.js
> +          ))}
```suggestion
          {categories.map(category => {
            const {id, name, list} = category;
            return (
            <MenuItem
              key={id}
              name={name}
              list={list}
            />
          )
          })}
```
구조분해할당해서 사용할 수 있겠네요!

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Menu/MenuList.scss
> +    width: 100%;
left, right 0을 부여한 경우에는 absoulte의 특성상 자연스레 좌우를 꽉 채우게 됩니다! width:100%는 불필요해보이네요!

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Menu/MenuList.scss
> +    text-align: center;
text-align은 position 보다는 스타일링에 영향을 덜미치는 속성이기에 아래로 내려가면 좋겠네요! 일전에 안내해드린 css 작성순서 부분 확인해보시고 전반적으로 작성순서 맞춰주세요!

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Menu/MenuList.scss
> +    .menuList {
다른 선택자들끼리는 한줄 공백 부여해주는게 가독성 상 좋습니다!

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Menu/SubMenu/SubMenuItem.js
> +    return <li className="subMenuItem ">{name}</li>;
className쪽에 불필요한 공백이 들어가 있는 것 같네요!

PR 올리신 후에는 반드시 github에서 File Changed 탭 확인해서 내가 작성한 코드에 실수는 없는지, 내가 의도하지 않은 작업물들이 올라가지 않았는지 확인하는 습관을 들여주세요! PR을 요청할 때의 마음가짐은 실제 내가 등록한 코드가 바로 배포되어서 유저들이 바로 사용하게 된다고 생각하고 해주세요.(물런 지금은 학습과정이니까 작업이 완료되지 않아도 피드백을 목적으로 추가기능구현중 라벨을 붙이고 PR을 요청할수도 있지만 리뷰 요청하기 전에는 스스로 한번 꼭 점검해주세요!!)

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Menu/SubMenu/SubMenuItem.scss
> +nav {
컴포넌트에 없는 요소에 대한 스타일링이 scss 파일에 포함되어있네요.
컴포넌트는 독립적이고 재사용될 수 있어야 합니다.
어떤 컴포넌트에 대한 스타일시트에서 컴포넌트 외의 요소에 대해서 접근해서 스타일을 부여한다면 그 컴포넌트는 독립적이라고 볼 수 없습니다.
컴포넌트의 스타일 시트는 해당 컴포넌트에 대한 스타일만 진행해주세요!

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Menu/SubMenu/SubMenuList.js
> +            {list.map((item, id) => (
id는 identify의 축약어로 오해할 수 있으니 index의 경우에는 명확히 index로 적어주시거나 축약하겠다면 관용적으로 많이 사용되는 idx를 사용하는게 좋습니다!

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Nav.js
> +    fetch('http://localhost:3000/data/ysLim/navCategories.json', {
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Nav.js
> +      method: 'GET',
get method는 기본값으로 생략가능합니다

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Nav.js
> +    return (
return 문 위쪽도 한줄 공백주는게 가독성에 좋습니다. 다른 문맥끼리는 공백이 들어가있는게 구분이 되어서 보기 좋습니다.

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Nav.js
>    render() {
render 위쪽에 한줄 공백 부여해주세요!

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Nav.js
> +                <img src="images/LogoLIKE.svg" alt="라이키 로고" />
```suggestion
                <img src="/images/LogoLIKE.svg" alt="라이키 로고" />
```
절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!

예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Nav.scss
> +}
이런 mixin은 공통적으로 많이 사용될 것 같은데 Nav안에 적는것보다 variables 에 적어둬서 어디서든 import해서 사용하기 좋게 만드는게 좋습니다

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Nav.scss
> +header {
- header 태그 처럼 빈번히 사용되는 태그로 스타일을 주는 건 depth에 무관하게 적용되어 의도치 않은 스타일링이 될 수 있습니다. 클래스 셀렉터(ex. `.foo`)를 사용해주세요.
- tag selector는 해당 요소 뿐만 아니라 동일한 태그로 선언된 다른 요소들에게도 영향을 미칠 여지가 너무 많기 때문에 추후 유지보수에 악영향을 미칠 수 있습니다.
- 스타일링을 줄 때는 요소마다 className을 부여하셔서 스타일링을 주시는게 좋습니다.

2021-11-03 02:50 UTC, younuk23 commented on src/components/Nav/Nav.scss
> +.preHeader {
전체적으로 최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅 하는 부분이 적용안되어있습니다. 이렇게 되면 동일한 className을 가진 다른 컴포넌트의 요소들에게도 영향을 미칠 수 있습니다.
**최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅** 적용해주세요

2021-11-03 02:50 UTC, younuk23 commented on src/components/TestComp/TCLogin.js
> +        style={{
inline style은 유지보수에 악영향을 줄 수 있으니 필요한 경우를 제외하고는 지양해주세요

2021-11-03 02:50 UTC, younuk23 commented on src/components/TestNav.js
> +        {loginModal ? <TCLogin toggle={this.toggleLogin} /> : null}
```suggestion
        {loginModal && <TCLogin toggle={this.toggleLogin} />}
```
굳이 삼항연산자 없이 and 연산자 통해서 표현 가능해보입니다

2021-11-03 02:50 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +    const re = /^[0-9\b]+$/;
변수명은 명확하게 의미가 드러나도록 지어주세요. 코드는 쓰여지는 것보다 읽히는 경우가 훨씬 더 많습니다. 이름만 보더라도 어떤 값을 담고 있는 변수인지 알 수 있게 지어주세요

2021-11-03 02:50 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +    if (value === '') {
```suggestion
    if (!value) {
```
falsy 값 특성 이용해서 위와 같이 표현할 수 있습니다

2021-11-03 02:50 UTC, younuk23 commented on src/pages/Detail/Detail.scss
> +        float: left;
float은 과거에는 요긴하게 쓰였지만 이제는 유지보수하기 힘든 속성으로 잘 사용하지 않습니다. flex 등으로 대체 가능한 경우가 대부분이니 대체해주세요

2021-11-03 02:54 UTC, younuk23 commented on src/components/Nav/Menu/MenuList.js
> +      <div className="menu">
- CSS 속성은 레이아웃에 영향을 많이 주는 순서대로, 인접 속성끼리 묶어서 
작성해주는게 좋습니다. 
- 일전에 안내해드린 [css 속성순서 컨벤션](https://www.notion.so/wecode/Westagram-JS-Refactoring-Checklist-dcff20de07b6449d89d82980e7af9cba#12ef362870c54d928ad6f56dab0b4b0e) 확인하시고 지켜서 작성해주세요

2021-11-03 11:33 UTC, tomlim2 reviewed
리뷰 감사합니다!

2021-11-03 11:33 UTC, tomlim2 commented on src/components/Nav/Nav.js
> +    fetch('http://localhost:3000/data/ysLim/navCategories.json', {
오 이건 진짜 몰랐어요! 감사합니다 ㅎㅎ

2021-11-03 11:33 UTC, tomlim2 commented on src/components/TestComp/TCLogin.js
> +        style={{
임시로 만든 페이지여서 인라인 스타일로 했습니다. 로그인 컴포넌트가 완성되는 데로 삭제하겠습니다.

2021-11-04 05:29 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요!! 그리고 계속해서 추가기능 구현중인신가요? 어제 저한테 머지 말씀하셔서 작업이 완료된것인가 싶어서 여쭤봅니다 만약 작업 완료된거라면 라벨 관리 잘해주세요! 라벨로 소통하는 것도 중요한 능력입니다

2021-11-04 05:29 UTC, younuk23 commented on src/components/Nav/Menu/MunuItem.scss
> +  &:hover .SubMenuList {
MenuItem 컴포넌트에서 SubMenuList의 스타일을 건드리고 있습니다. 컴포넌트가 독립적으로 분리가 안되어있는 것 같네요!!

2021-11-04 05:29 UTC, younuk23 commented on src/components/Nav/Nav.js
> +    fetch('./data/ysLim/navCategories.json')
이제 data폴더 안에 이름으로 폴더를 나눌 필요는 없습니다. 폴더를 구분하신다면 기능별로 구분하시는게 좋습니다!

2021-11-04 05:29 UTC, younuk23 commented on src/components/TestNav.js
>    }
어떤 목적의 테스트용 파일인가요? PR은 머지되면 바로 프로덕션에 배포된다는 생각으로 작업하셔야 합니다!!
불필요한 테스트용 코드가 그대로 프로덕션에 들어가면 안되겠죠? 명확히 목적이 있지 않다면 삭제해주세요!

2021-11-04 05:29 UTC, younuk23 commented on src/pages/Detail/Detail.js
> +        {loginModal ? <TCLogin toggle={this.toggleLogin} /> : null}
```suggestion
        {loginModal && <TCLogin toggle={this.toggleLogin} />}
```
굳이 삼항연산자 사용 안하셔도 됩니다!

2021-11-04 05:29 UTC, younuk23 commented on src/pages/Detail/DetailInfo/DetailInfo.js
> +      <div key={id} className="DetailInfo">
map에서 return 되는 배열형태가 아닌데 key를 부여하신 이유가 있나요?? 불필요한 코드입니다!

2021-11-04 08:45 UTC, younuk23 approved these changes
LGTM 👍 
코멘트 드린 사항은 다음 작업에서 반영해주세요!
코멘트 드린 코드라인 뿐만 아니라 전반적으로 동일한 부분 있는지 파악해서 처리해주세요!
그리고 가독성위해서 한줄 공백 주는 것, Test 컴포넌트 파일들 삭제하는 것 반영 안되어있는데 다음부터는 꼼꼼히 확인하고 다 반응 하거나 의견이 있으시면 코멘트로 의견 주는 식으로 진행해주세요!

2021-11-04 08:45 UTC, younuk23 commented on src/components/Nav/Menu/MenuItem.js
> +        <Link to={`./product/${id}`}>
여기도 절대경로로 적어주는게 안전합니다!

2021-11-04 08:45 UTC, younuk23 commented on src/components/Nav/Menu/MenuItem.js
> +        <div className="MenuItemInner">
여기는 PascalCase로 작성할 이유가 없는데 파스칼 케이스로 작성하신걸로 보입니다!

2021-11-04 08:45 UTC, younuk23 commented on src/components/Nav/Nav.js
> +    fetch('./data/nav/navCategories.json')
절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!

예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.

2021-11-04 08:45 UTC, merged

2021-11-04 08:48 UTC, tomlim2 commented
여기에 코멘트 다는거 맞죠? 알겠습니다! 다음 작업때에 반영하도록 하겠습니다. 감사합니다 ㅎㅎ