[26기 전지완] Add: Main Page Upload
wecode-bootcamp-korea/26-1st-LIKE-frontend pull request #2
Opened 2021-11-02 16:53 UTC by jiwanjeon

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 기본적인 Main UI 구현
- Aside Section에서 색상/사이즈 선택시 Content Body에서 해당하는 제품 보여주기
- Content Body에서 카테고리(전체,신발,의류,용품) 선택시 해당하는 제품 보여주기
- 제품을 눌렀을시 상세페이지로 이동
- 반응형

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. Main UI
- 처음에는 하드코딩으로 Aside & Content Body에 있는 UI를 하나하나 구현하여 확인 작업
- 반복되는 부분을 찾아(Aside: 색상 & Content Body: Product Layout) mapping
- Mock Data를 만들어서(JSON) 백에서 데이터를 가져왔을때 잘 되는지 확인(Content Body에 Products Information)
2. 색상/사이즈에 해당하는 제품 보여주기
- 구현 예정
3. 카테고리(전체,신발,의류,용품) 선택시 
- 구현 예정
4. 상세페이지 이동
- 구현 예정
5. 반응형
- 구현 예정

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 반복이 많이 되는 부분을 찾아 mapping을 활용하여 코드 간결화
- Grid 활용
- Input's checkBox를 Styling을 하기위해선 지금까지 했던 방법과는 다른 방법을 사용해야함
ex) Button에서 styling했던 방식을 적용할수 없음

<br />

## :: 기타 질문 및 특이 사항
- Aside부분에 색상부분이 반복되서 Mapping을 하고자 했는데 flexbox속성을 활용을 해봐도 생각한거와는 다른 결과가 계속 나와서 도움을 요청합니다! 추가적으로, 이 부분에서 mapping을 했을때 Input의 배경 색깔을 scss에 states값을 전달 할 수가 없어서 어쩔수 없이 inline stlying을 했는데 괜찮은 방법인지 여쭤봅니다!

2021-11-03 02:02 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +                <a>Men</a>
a -> span으로 바꿀 예정

2021-11-03 02:03 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +                {this.state.productsInfo &&
...??

2021-11-03 02:05 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +                {this.state.productsInfo &&
const { productsInfo }= this.state;

2021-11-03 03:22 UTC, younuk23 commented
구현목표에 너무 많은 목표들이 있는 것 같습니다. 목표별로 브랜치를 적절하게 분리하는게 좋을 것 같네요 한 브랜치에서 전체 작업을 다 하기엔 방대해보이네요 이미 700줄의 수정사항이 있습니다!

2021-11-03 03:27 UTC, younuk23 commented
Aside부분에 색상부분이 반복되서 Mapping을 하고자 했는데 flexbox속성을 활용을 해봐도 생각한거와는 다른 결과가 계속 나와서 도움을 요청합니다! => 네 라운지에서 한번 질문주세요!!

추가적으로, 이 부분에서 mapping을 했을때 Input의 배경 색깔을 scss에 states값을 전달 할 수가 없어서 어쩔수 없이 inline stlying을 했는데 괜찮은 방법인지 여쭤봅니다!
=> 네 불필요한 inline style 은 지양해야하지만, 판단해서 필요한 경우에는 적용하셔도 됩니다!

푸쉬하시고 나서 사이더가 리뷰 달아준 사항 반영해주세요! 사이더 리뷰 반영되고 나면 다시 확인하겠습니다. 지금은 정리되지 않은 부분이 많아 리뷰하기가 힘드네요!

2021-11-04 05:31 UTC, younuk23 commented on src/pages/Main/Main.js
> +                {this.state.productsInfo &&
불필요한 코멘트는 삭제해주세요, 코멘트로 리뷰어와 소통하는데 불필요한 코멘트가 남아있으면 안됩니다

2021-11-04 05:32 UTC, younuk23 commented
PR 제목은 최근 작업 주제가 아니라 이 브랜치의 핵심 작업 내용을 적으시면 됩니다!!

2021-11-04 05:33 UTC, younuk23 commented
어제 말씀드린 것 처럼 push 하신 후에는 Sider가 리뷰 단 것 없는지 확인, 있을 경우엔 수정, File Changed 탭 확인해서 변경사항 체크 반드시 진행해주세요!

2021-11-04 05:58 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요 지완님!

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.js
> +    fetch('http://localhost:3000/data/MainProducts.json', {
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다
그리고 json 파일명 이름을 PascalCase로 할 이유는 없어보입니다!

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.js
> +      method: 'GET',
get method는 기본값으로 생략가능합니다

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.js
> +    return (
return 위에 한줄 공백 있는게 가독성 상 좋습니다. 다른 문맥들끼리는 공백을 통해서 가독성에 신경써주세요

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.js
> +      <div>
네스팅을 통해서 이 컴포넌트의 스타일이 다른 컴포넌트에게 영향을 미치지 않도록 컴포넌트의 최상위 태그의 className은 컴포넌트 명과 동일하게 해주세요 일반적으로 className은 팀 컨벤션에 따라 camelCase또는 snake_case로 짓는게 일반적이지만 최상위 태그의 경우에는 컴포넌트 명과 동일하게 PascalCase로 지어주는 게 좋습니다(유니크하게 지어서 다른 className과 중복되지 않게 하기 위해서)

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.js
> +        <div className="mainWrapper">
전체적으로 div가 많이 사용되었는데 sementic tag 사용 한번 더 생각하고 적용해보시면 좋아보이네요!

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.js
> +                <select name="dog-names" id="dog-names">
- `id` 보다는 `className` 을 활용해주시기 바랍니다.
- HTML에서  `id` 는 문서 내에서 유일해야 합니다. 이러한 이유로 단일 요소를 다루는 경우 `id`를 사용할 수 있습니다.
- 하지만 정말로 해당 요소에 대한 이벤트나 스타일 핸들링이 프로젝트 전체에서 단 한번만 사용 되는지 충분히 고민해야합니다. 일반적으로 컴포넌트는 재사용 될 수 있기 때문에 같은 요소가 여러번 생성될 수 있습니다. 이러한 이유로 보통의 경우에는 `className` 을 사용합니다.

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.js
> +                        ></label>
id 사용 지양해주세요, label을 input에 매칭시키기 위함이라면 <label><input /></label> 구조로 한다면 id및 htmlFor 속성 없이도 동일한 동작을 수행할 수 있습니다

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.js
> +                  <button title="230">250</button>
title은 어떤 attribute이고 왜 부여하신건가요??

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.js
> +                              alt="productImage"
alt는 대체텍스트로도 사용되므로 일반 영문법에 맞춰서 작성해주시는게 좋습니다

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.scss
> +      flex-direction: row;
row는 기본값입니다!

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.scss
> +      .sectionTitleCategory {
다른 셀렉터끼리는 공백 부여해주세요, 그리고 스타일을 부여하지 않을거면 굳이 className을 부여할 필요 없습니다!(최상위 태그를 제외하고)

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.scss
> +    width: 100%;
불필요한 코드입니다 왜 불필요한지 코멘트로 답글 달아주세요!

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.scss
> +      .HorizontalLine {
className은 최상위 태그를 제외하고는 PascalCase 사용은 지양해주세요

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.scss
> +            justify-content: center; // this will also help center the content
불필요한 주석은 다 삭제해주세요

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.scss
> +            label {
- 빈번히 사용되는 태그로 스타일을 주는 건 depth에 무관하게 적용되어 의도치 않은 스타일링이 될 수 있습니다. 클래스 셀렉터(ex. `.foo`)를 사용해주세요.
- tag selector는 해당 요소 뿐만 아니라 동일한 태그로 선언된 다른 요소들에게도 영향을 미칠 여지가 너무 많기 때문에 추후 유지보수에 악영향을 미칠 수 있습니다.
- 스타일링을 줄 때는 요소마다 className을 부여하셔서 스타일링을 주시는게 좋습니다.

2021-11-04 05:58 UTC, younuk23 commented on src/pages/Main/Main.js
> +                      <div className="productsContainer" key={idx}>
메인 컴포넌트에서 너무 방대한 내용이 있는 것 보다 이 부분은 따로 컴포넌트화 해보는게 좋아보입니다

2021-11-04 06:00 UTC, younuk23 commented
그리고 추가기능 여기서 구현하기보다는 브랜치 분리해서 하는게 나아보입니다 더이상 추가적으로 붙을 내용 없다면 추가작업 진행중 라벨은 제거해주세요!!

2021-11-04 06:28 UTC, jiwanjeon commented
> PR 제목은 최근 작업 주제가 아니라 이 브랜치의 핵심 작업 내용을 적으시면 됩니다!!

아 네 감사합니다 ㅎ 변경했습니다!

2021-11-04 06:32 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +    fetch('http://localhost:3000/data/MainProducts.json', {
아 저번 session때 있던 참고자료 그대로 활용했는데 처음알았네요! 좋은 정보 감사합니다 ㅎ

2021-11-04 06:33 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +      method: 'GET',
수업때 언급해주셨던 내용 기억납니다! 안쓰면 자동으로 get method로 인지한다구 언급해주셔서 감사합니다 ㅎ

2021-11-04 06:33 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +    return (
네!

2021-11-04 06:36 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +      <div>
@younuk23  최상위 div mainWrapper --> MainWrapper로 바꾸는게 좋다 라는 말씀이시죠?!

2021-11-04 06:38 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +        <div className="mainWrapper">
@younuk23 제가 지금 aside하나만 썼는데 확인해봤을떄 article정도만 더 추가될거같은데 혹시 다른거 더 쓸게 있을까요?

2021-11-04 06:42 UTC, jiwanjeon commented on src/pages/Main/Main.scss
> +            justify-content: center; // this will also help center the content
넵!

2021-11-04 06:50 UTC, jiwanjeon commented on src/pages/Main/Main.scss
> +    width: 100%;
@younuk23 이유를 생각해봤을때 flex를 쓰지 않아도 contentswrapper안에 있는 aside와 contentsbody 둘의 위치를 조정해줄 수 있을거같아서 인거같은데... 저는 원래 첨에는 display: flex랑 flex-dricetion: row 이 두개로 전체적인 틀을 잡아줄려고 했는데 신기하게도 제가 실수로 flex-direction:row를 누락했는데 display:flex만 해도 정렬이 되네요...

2021-11-04 06:50 UTC, jiwanjeon commented on src/pages/Main/Main.scss
> +            label {
아 네 알겠습니다!

2021-11-04 06:52 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +                      <div className="productsContainer" key={idx}>
아 네 감사합니다! 안그래도 trello-backlog에 컴포넌트화 카드 어제 만들어놨습니다 :)

2021-11-04 06:52 UTC, jiwanjeon commented
> 그리고 추가기능 여기서 구현하기보다는 브랜치 분리해서 하는게 나아보입니다 더이상 추가적으로 붙을 내용 없다면 추가작업 진행중 라벨은 제거해주세요!!

아 어제 질문하러 갔을때 코멘트 주셔서 그렇게 할 예정입니다! :)

2021-11-04 07:14 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +                <select name="dog-names" id="dog-names">
아 네 인지하겠습니다!

2021-11-04 07:17 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +                  <button title="230">250</button>
나중에 버튼 추가 설명하려고 쓴건데 검색해보니 지양해야한다구 나오네요. "레이블 텍스트에 대한 추가 설명을 title 속성으로 제공하는 것은 스크린리더의 정책 및 호환성 측면에서 적절하지 않습니다. 스크린리더 문제 외에도 title 속성을 사용할 경우 여러 가지 사용성 이슈가 발생할 수 있습니다." 이유들로 인해서

2021-11-04 07:18 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +                              alt="productImage"
아 그럼 image of prodiction으로 바꾸겠습니다!

2021-11-04 07:21 UTC, jiwanjeon commented on src/pages/Main/Main.scss
> +      flex-direction: row;
아 놓쳤었네요 감사합니다!

2021-11-04 08:16 UTC, jiwanjeon commented on src/pages/Main/Main.scss
> +    width: 100%;
==> block vs in-block elements / block(width 100% 의미가 없음)

2021-11-05 05:29 UTC, younuk23 commented
query parameter을 쓸때 주소를 백에다가 보내줘야 하는데 백에서 통신할때 저한테 준 data 리스트중에 카테고리(신발,옷,용품)가 없어 인자값을 제가 받기가 어려운데 그래서 저는 지은님(백)한테 리스트를 추가해달라고 했는데 맞는건지 혹은 놓친부분이 있는지(제가 봐도 잘 이해 못해겠는데 멘토링 시간때 더 설명해보겠습니다)
=> 질문을 할 때도 잘 정리해서 1.목표 2.문제상황 3.내가 생각한 문제 해결 방안 4.그런데 어디서 막혔는지 등을 잘 정리하셔서 질문하시는게 굉장히 중요하고 요구되는 역량입니다!! 잘 정리하셔서 라운지때 질문 주세요!! 답변드리겠습니다!!

2021-11-05 05:34 UTC, younuk23 requested changes
기존에 리뷰드린 사항이 반영 안된상태로 다시 재리뷰요청을 하신 것 같습니다! 다 반영해주시고 꼼꼼히 확인해주세요!

2021-11-05 05:34 UTC, younuk23 commented on src/pages/Main/Main.js
> +      // method: 'GET',
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2021-11-05 05:34 UTC, younuk23 commented on src/pages/Main/Main.js
> +    console.log('match', this.props.match.id);
불필요한 주석은 삭제해주시고 가이드 드렸다시피 푸쉬하신 뒤에 사이더 리뷰 반영 및 파일 체인지탭 반드시 확인해주세요 기본적인 소양입니다!

2021-11-05 05:34 UTC, younuk23 commented on src/pages/Main/Main.js
> +        <div className="mainWrapper">
한번 고민해보셔서 적용해보세요!! 그 뒤에 피드백 드리겠습니다

2021-11-05 05:34 UTC, younuk23 commented on src/pages/Main/Main.js
> +      <div>
최상위 태그에 className이 부여되어있지 않고 차상위에 부여되어있으며 className이 camelCase로 작성된 부분말씀드린 것입니다! 반영해주세요!! 답을 확인하기보다는 스스로 고민하셔서 적용해보신 다음에 피드백 받는 방식으로 진행하시는 것을 권장드립니다!!(물론 내가 작성한 코드에는 반드시 명확한 근거가 있어야합니다!)

2021-11-05 05:34 UTC, younuk23 commented on src/pages/Main/Main.scss
> +    width: 100%;
row는 기본값입니다!

2021-11-05 09:09 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +      <div>
네!

2021-11-05 09:09 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +        <div className="mainWrapper">
아 네 알겠습니다 ㅎ

2021-11-08 01:28 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +    console.log(this.props.history.location.pathname);
콘솔 확인하고 싶어서 넣었는데 주석 처리 해놓겠습니다

2021-11-08 01:29 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +    console.log(e);
콘솔 확인하고 싶어서 넣었는데 주석 처리 해놓겠습니다

2021-11-08 01:29 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +import React, { Component, useState } from 'react';
useState값을 사용하지 않아 지우겠습니다

2021-11-08 01:30 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +    console.log(this.props.history.location.pathname);
바로 하겠습니다!

2021-11-08 01:30 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +    const currentURL = this.props.history.location.pathname;
바로 하겠습니다!

2021-11-08 01:30 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +    if (this.state.selectedItems.includes(e.target.value)) {
바로 하겠습니다!

2021-11-08 01:30 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +      newSelected = this.state.selectedItems.filter(
바로 하겠습니다!

2021-11-08 01:30 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +      newSelected = [...this.state.selectedItems, e.target.value];
바로 하겠습니다!

2021-11-08 01:30 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +    const currentURL = this.props.history.location.pathname;
바로 하겠습니다!

2021-11-08 01:30 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +                        checked={this.state.selectedItems.includes(
바로 하겠습니다!

2021-11-08 02:21 UTC, saengmotmi reviewed
리뷰 확인해주세요!

2021-11-08 02:21 UTC, saengmotmi commented on src/pages/Main/Main.scss
> +              border-radius: 50%;
- 연관된 속성 끼리는 모아서 작성해주시고 (ex. display flex)
- 새로운 셀렉터 앞에서는 한줄 공백 주세요

2021-11-08 02:21 UTC, saengmotmi commented on src/pages/Main/Main.scss
> +        .span {
push 하신 다음에 PR 내에서 files changed 한번 살펴보면 찾아서 정리할 수 있는 부분인 것 같습니다 꼼꼼히 봐주세요

2021-11-08 02:21 UTC, saengmotmi commented on src/pages/Main/Main.scss
> +          flex-direction: row;
위 리뷰 내용에서 flex direction row가 기본 값인 걸 이미 알고 계실 것 같습니다. 같은 내용 있다면 찾아서 수정해주세요

2021-11-08 02:21 UTC, saengmotmi commented on src/pages/Main/ProductsInfo/Products.js
> +    //  어떤 props를 parent에서 child로 전달할 수 있을지 생각해보세요!
리뷰 받은 내용이신가요? master에 합쳐질 코드라고 생각하시고 정리 잘 해주세요

2021-11-08 02:21 UTC, saengmotmi commented on public/data/MainProducts.json
> +    "size": "230",
- id는 완전히 고유한 값이어야 합니다 물론 mock data이긴 합니다만 일반적으로 shoes 같은 문자열을 id로 사용하지는 않습니다
- 신발 size가 문자열로 표현되는게 더 좋을까요?

2021-11-08 02:21 UTC, saengmotmi commented on public/data/MainProducts.json
> +      "gold",
백엔드와 color를 문자열로 주고 받기로 했나요?

2021-11-08 02:21 UTC, saengmotmi commented on public/data/MainProducts.json
> +    "ecoFriendly": "친환경소재",
어떤 부분은 스네이크케이스로, 어떤 부분은 카멜 케이스로 작성되어 있는 것 같습니다 특별한 이유가 있나요?

2021-11-08 02:21 UTC, saengmotmi commented on src/pages/Main/Main.js
> +    this.handleChange = this.handleChange.bind(this);
화살표 함수를 사용한다면 bind 해주지 않아도 됩니다

2021-11-08 02:21 UTC, saengmotmi commented on src/pages/Main/Main.js
> +  // const API = "DASDDADDAD" => 컴포넌트 마다 다 적용할수x
불필요한 주석 가급적 남겨두지 않는게 좋습니다

2021-11-08 02:21 UTC, saengmotmi commented on src/pages/Main/Main.js
> +                        id={idx}
label 태그로 input 감싸면 id, htmlFor 불필요합니다

2021-11-08 02:21 UTC, saengmotmi commented on src/pages/Main/Main.js
> +                    state: { message: 'hello, im a passed message!' },
state 넘기는거 필요한가요?

2021-11-08 02:21 UTC, saengmotmi commented on src/pages/Main/Main.js
> +              {productsInfo &&
productsInfo가 이미 배열이기 때문에(항상 참값이기 때문에) 불필요한 조건부 렌더링입니다

2021-11-08 02:22 UTC, saengmotmi commented
PR 내용에 replaceState가 있던데 혹시 사용되나요?

2021-11-08 06:27 UTC, jiwanjeon commented on src/pages/Main/Main.scss
> +              border-radius: 50%;
수정완료했습니다!

2021-11-08 06:28 UTC, jiwanjeon commented on src/pages/Main/Main.scss
> +        .span {
확인 더 철처히 하겠습니다!

2021-11-08 06:29 UTC, jiwanjeon commented on src/pages/Main/Main.scss
> +          flex-direction: row;
아 제가 더 썼는지 확인도 안했네요 죄송합니다

2021-11-08 06:29 UTC, jiwanjeon commented on src/pages/Main/ProductsInfo/Products.js
> +    //  어떤 props를 parent에서 child로 전달할 수 있을지 생각해보세요!
네 리뷰 받은 내용인데 아직 좀 더 고민중입니다!

2021-11-08 06:30 UTC, jiwanjeon commented on public/data/MainProducts.json
> +      "gold",
ㄴ네 문자로 주고받기로 했습니다!

2021-11-09 00:45 UTC, jiwanjeon commented on public/data/MainProducts.json
> +    "size": "230",
아직 Mock Data를 제가 변경하지 못했는데 ssarchParams 해결하면서 동시에 MockData 바로 수정하겠습니다

2021-11-09 00:47 UTC, jiwanjeon commented on public/data/MainProducts.json
> +    "ecoFriendly": "친환경소재",
저의 프론트에서는 Camel Case하기로 했는데 백에서는 Snake Case하기로 했나봐요 그래서 데이터 서로 주고받을때 Mock Data에서는 저렇게 사용했습니다

2021-11-09 00:47 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +  // const API = "DASDDADDAD" => 컴포넌트 마다 다 적용할수x
네!

2021-11-09 00:48 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +    this.handleChange = this.handleChange.bind(this);
아 제가 조금 더 공부해서 확인해보겠습니다

2021-11-09 00:53 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +                        id={idx}
아 네 알겠습니다!

2021-11-09 00:54 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +                    state: { message: 'hello, im a passed message!' },
아 제가 값넘겨주려는거 확인하려다가 안지운거 같습니다!

2021-11-09 01:01 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +                        id={idx}
제가 이 부분을 Stackoverflow에서 도움받아서 해결 한 부분이여서 "아 아렇게 쓰는거구나"하고 이해만 하고 넘어가긴 했는데 종택님 커멘트 듣고 id랑 htmlfor빼면 제가 원하는 inputt checkbox가 실행되질 않아서 오후 세션에 한번 여쭤보겠습니다. 혹시 몰라서 링크 남깁니다! "https://stackoverflow.com/questions/69872313/input-checkbox-didnt-work-what-i-expected/69872796?noredirect=1#comment123512396_69872796"

2021-11-09 01:03 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +              {productsInfo &&
아 네 확인했습니다.

2021-11-09 01:04 UTC, jiwanjeon commented on public/data/MainProducts.json
> +      "gold",
> PR 내용에 replaceState가 있던데 혹시 사용되나요?

어제 종택님하고 같이 확인한 내용입니다!

2021-11-09 08:18 UTC, jiwanjeon commented on src/pages/Main/Main.js
> +  ㄴ;
@saengmotmi 종택님 혹시 이거 말씀하셨던건가요? 지금은 지우긴 했는데

2021-11-10 05:05 UTC, saengmotmi commented
@jiwanjeon 그간 고생 많으셨습니다! LGTM 👍

2021-11-10 05:05 UTC, merged

2021-11-10 16:06 UTC, jiwanjeon commented
> @jiwanjeon 그간 고생 많으셨습니다! LGTM 👍

종택님 젝가 모르고 푸쉬를 브랜치를 만들지도 않구 feature/Main에 푸쉬 했는데 괜찮나요...?ㅠ