[26기 신유진]Add:로그인 레이아웃 구현,메인페이지 연동
wecode-bootcamp-korea/26-1st-LIKE-frontend pull request #3
Opened 2021-11-04 04:14 UTC by newjinny

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 UI
- 아이디,비밀번호 잘못 입력시 알림 메세지
- 메인페이지,회원가입페이지 연동
- 체크박스 컬러 변경
- 로그인 버튼 hover
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입 클릭시 <Link> 사용하여 signup페이지로 이동
2. 로그인 버튼 hover와 커서모양 변경 완료
3.  로그인 버튼 클릭시 main으로 이동  (로그인 텍스트 클릭시 이동으로 해서 다시 버튼 클릭시 이동할 수 있도록 수정해야함)
4. 체크박스 클릭시 배경컬러 설정 (scss에 :checked 사용했지만 적용되지 않아 방법을 아직 찾는 중)
5. 잘못 입력시 알림 메세지는 아직 하는 중

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 

<br />

## :: 기타 질문 및 특이 사항
- 체크박스 컬러 변경 하는 방법이 잘 적용되지 않는데 혹시 직접 박스를 만들어서 적용해야하는지 궁금해요.

2021-11-04 06:02 UTC, younuk23 commented
PR본문에서 구현사항 설명 작성시 조금 더 어떻게(HOW)에 초점을 맞춰서 작성해주세요!! 지금은 무엇을 했는지에 대해서만 기술되어 있어 보입니다! 구현사항을 잘 적으면서 내가 어떻게 구현했는지 스스로 이해도를 점검해볼 수 있으며 나중에 내가 어떤 고민을 하고 문제를 어떻게 해결했는지 점검해보면서 스스로를 회고해볼 수 있는 좋은 자산이 됩니다!

- 그리고 Push후에서 사이더에서 리뷰 달아준 사항은 바로 확인 및 수정해서 다시 push 해주세요! 파일체인지 탭 보면서 스스로 작업 내용 점검도 반드시 해주시고요!

2021-11-04 06:12 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요 유진님!

2021-11-04 06:12 UTC, younuk23 commented on src/components/Login/Login.js
> +      <section className="login">
네스팅을 통해서 이 컴포넌트의 스타일이 다른 컴포넌트에게 영향을 미치지 않도록 컴포넌트의 최상위 태그의 className은 컴포넌트 명과 동일하게 해주세요 일반적으로 className은 팀 컨벤션에 따라 camelCase또는 snake_case로 짓는게 일반적이지만 최상위 태그의 경우에는 컴포넌트 명과 동일하게 PascalCase로 지어주는 게 좋습니다(유니크하게 지어서 다른 className과 중복되지 않게 하기 위해서)

2021-11-04 06:12 UTC, younuk23 commented on src/components/Login/Login.js
> +              onChange={this.handleIdInput}
input의 value값이 부여되어 있지 않습니다 value값 부여를 통해서 input을 컨트롤 할 수 있게 해주세요!!

2021-11-04 06:12 UTC, younuk23 commented on src/components/Login/Login.js
> +  };
id와 pw 핸들링 하는 함수 input의 name attribute와 javascript 계산된 속성명 특성 이용해서 한 함수로 처리 가능해보입니다!

2021-11-04 06:12 UTC, younuk23 commented on src/components/Login/Login.js
> +            // onClick={this.goToMain}
불필요한 주석은 삭제해주세요

2021-11-04 06:12 UTC, younuk23 commented on src/components/Login/Login.scss
> +section{
최상위 태그에 className 부여하고 전체적으로 네스팅 해주세요! 이상태면 프로젝트 내부의 모든 section tag에 다 영향을 미칩니다!

2021-11-04 06:12 UTC, younuk23 commented on src/components/Login/Login.scss
> +    margin-bottom: 4rem;
CSS 속성은 레이아웃에 영향을 많이 주는 순서대로, 인접 속성끼리 묶어서 
작성해주는게 좋습니다. 
- 일전에 안내해드린 [css 속성순서 컨벤션](https://www.notion.so/wecode/Westagram-JS-Refactoring-Checklist-dcff20de07b6449d89d82980e7af9cba#12ef362870c54d928ad6f56dab0b4b0e) 확인하시고 지켜서 작성해주세요

2021-11-04 06:12 UTC, younuk23 commented on src/components/Login/Login.scss
> +
너무 많은 공백이 들어가 있습니다. 구분하기 위한 공백은 한줄만 부여해주세요

2021-11-04 06:12 UTC, younuk23 commented on src/components/Login/Login.scss
> +    button {
- div,button 태그 처럼 빈번히 사용되는 태그로 스타일을 주는 건 depth에 무관하게 적용되어 의도치 않은 스타일링이 될 수 있습니다. 클래스 셀렉터(ex. `.foo`)를 사용해주세요.
- tag selector는 해당 요소 뿐만 아니라 동일한 태그로 선언된 다른 요소들에게도 영향을 미칠 여지가 너무 많기 때문에 추후 유지보수에 악영향을 미칠 수 있습니다.
- 스타일링을 줄 때는 요소마다 className을 부여하셔서 스타일링을 주시는게 좋습니다.

2021-11-04 06:12 UTC, younuk23 commented on src/components/Login/Login.scss
> +}
prettier 설정이 안되어있는것 같은데 혹시 vscode에 prettier 설치 안되어계신가요?? 세팅 잘 안되시는 거면 도와드릴테니까 말씀해주세요!

2021-11-04 06:13 UTC, younuk23 commented
체크박스 컬러 변경 하는 방법이 잘 적용되지 않는데 혹시 직접 박스를 만들어서 적용해야하는지 궁금해요.
=> label tag를 이용하는 방법이 있을 것 같습니다 how to make custom checkbox 등의 키워드로 검색하시면 레퍼런스 많이 나올 것 같네요!!

2021-11-05 05:35 UTC, younuk23 commented
유진님 어떻게 진행하고 계신가요?? 혹시 다른 것 진행하고 계시는거면 리뷰 사항 반영 최우선적으로 진행해주세요!!
컨플릭도 해결해주세요!!

2021-11-09 06:50 UTC, newjinny commented on src/components/Login/Login.js
> +      <section className="login">
수정했어요! 확인 부탁들요~

2021-11-09 06:51 UTC, newjinny commented on src/components/Login/Login.js
> +      <section className="login">
수정했어요! 확인 부탁드려요~

2021-11-09 06:52 UTC, newjinny commented on src/components/Login/Login.js
> +              onChange={this.handleIdInput}
placeholder랑 value를 같이 쓸 필요가 없다고 생각했었어요! 수정했어요!!

2021-11-09 06:52 UTC, newjinny commented on src/components/Login/Login.js
> +  };
넵 다 수정했습니다!!

2021-11-09 06:54 UTC, newjinny commented on src/components/Login/Login.scss
> +section{
안그래도 회원가입이랑 겹쳐서 난리났었어요..중요한 걸 배웠네요!

2021-11-10 15:56 UTC, saengmotmi commented
@newjinny 유진님 sider에서 달아준 코멘트 일단 해결해주세요

2021-11-11 13:28 UTC, merged